# Generated by Django 3.2.17 on 2023-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Город'),
        ),
    ]
